export enum PlaceType {
    shoes = "Shoes",
    kids = "Kids",
    home = "Home",
    baby = "Baby",
    music = "Music",
    toys = "Toys",
    tools = "Tools",
    garden = "Garden",
    jewelry = "Jewelry",
    sports = "Sports",
    books = "Books",
    computers = "Computers",
    industrial = "Industrial",
    grocery = "Grocery",
    automotive = "Automotive",
    outdoors = "Outdoors",
    movies = "Movies",
    electronics = "Electronics",
    games = "Games",
    beauty = "Beauty",
    clothing = "Clothing",
    health = "Health"
}